/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Справочник вузов
         * @description Список для выбора вуза в профиле.
         *
         *     Цифры приёмной кампании демонстрационные и помечены полем `demo_fields`
         *     в каждой записи (уточнения У4, Д3).
         */
        get: operations["list_universities_api_v1_universities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий профиль */
        get: operations["read_profile_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить профиль
         * @description Меняет статус, вуз, группу или имя.
         *
         *     Пропущенное поле не меняется. Ответ содержит пересчитанный блок `access`:
         *     какие разделы открылись или закрылись, решает сервер, а не клиент (ТЗ 3).
         */
        patch: operations["update_profile_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подтвердить статус студента
         * @description Переводит профиль в подтверждённое состояние.
         *
         *     Реальной проверки учебной почты и загрузки документов нет — это осознанная
         *     заглушка (уточнение У7). Условия подтверждения проверяются настоящие
         *     (уточнение У17), поэтому подключение реальной проверки затронет ровно одну
         *     функцию.
         */
        post: operations["confirm_verification_api_v1_users_me_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Живость процесса */
        get: operations["liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Готовность к запросам */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DependencyStatus */
        DependencyStatus: {
            /** Error */
            error?: string | null;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LivenessResponse */
        LivenessResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * ProfileAccessOut
         * @description Какие разделы открыты. Считает сервер (ТЗ 3).
         */
        ProfileAccessOut: {
            /**
             * Answer Questions
             * @description Право отвечать в блоке 5 (уточнение У17)
             */
            answer_questions: boolean;
            /**
             * Food
             * @description Блок 7 «Где покушать»
             */
            food: boolean;
            /**
             * Schedule
             * @description Блок 4 «Расписание и дедлайны»
             */
            schedule: boolean;
        };
        /** ProfileOut */
        ProfileOut: {
            access: components["schemas"]["ProfileAccessOut"];
            /** Display Name */
            display_name: string;
            /** Group Name */
            group_name: string | null;
            /** Is Verified Student */
            is_verified_student: boolean;
            /** Max User Id */
            max_user_id: string;
            /**
             * Needs Display Name
             * @description Имя не получено от платформы и не введено пользователем — профиль должен показать строку ввода имени (уточнение У6).
             */
            needs_display_name: boolean;
            /** Points Balance */
            points_balance: number;
            status: components["schemas"]["UserStatus"];
            university: components["schemas"]["UniversityOut"] | null;
        };
        /**
         * ProfileUpdateIn
         * @description Частичное обновление профиля.
         *
         *     Пропущенное поле означает «не менять». Очистки полей нет: вуз и группа
         *     выбираются из списка, имя не стирается.
         */
        ProfileUpdateIn: {
            /** Display Name */
            display_name?: string | null;
            /** Group Name */
            group_name?: string | null;
            status?: components["schemas"]["UserStatus"] | null;
            /** University Id */
            university_id?: number | null;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Dependencies */
            dependencies: components["schemas"]["DependencyStatus"][];
            /** Status */
            status: string;
        };
        /** UniversityOut */
        UniversityOut: {
            /** Admission Deadline */
            admission_deadline: string | null;
            /** Budget Places */
            budget_places: number | null;
            /** City */
            city: string;
            /**
             * Demo Fields
             * @description Поля с демонстрационными значениями: цифры приёмной кампании не являются официальными данными и должны быть помечены в интерфейсе.
             */
            demo_fields?: string[];
            /** Has Dormitory */
            has_dormitory: boolean;
            /** Id */
            id: number;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Tuition Price */
            tuition_price: number | null;
        };
        /**
         * UserStatus
         * @description Статус пользователя (ТЗ 1.3).
         *
         *     Значение по умолчанию — «Абитуриент»: онбординга нет, новый пользователь
         *     попадает сразу в главное меню (уточнение У5).
         * @enum {string}
         */
        UserStatus: "school" | "applicant" | "student";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_universities_api_v1_universities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversityOut"][];
                };
            };
        };
    };
    read_profile_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    update_profile_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_verification_api_v1_users_me_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
