/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/career-test/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Вопросы теста
         * @description Десять вопросов с вариантами в порядке макета.
         *
         *     Опознание пользователя здесь не требуется по смыслу, но остаётся общим для
         *     всего API: тест начинается сразу, без регистрации (уточнение У5).
         */
        get: operations["read_questions_api_v1_career_test_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-test/results/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Последний результат */
        get: operations["read_latest_result_api_v1_career_test_results_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-test/results/{result_id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Сохранить результат в профиль
         * @description Прикрепляет результат к профилю и начисляет +50 баллов (уточнение У21).
         *
         *     Эндпоинта нет в тех. ТЗ 3.2, потому что там результат сохраняется сразу при
         *     отправке ответов. Кнопка «Сохранить в профиль» из продуктового ТЗ (п. 1.6)
         *     требует отдельного действия — и именно за него начисляются баллы.
         */
        post: operations["save_result_api_v1_career_test_results__result_id__save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-test/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отправить ответы
         * @description Считает топ-3 направления, просит объяснение у LLM и сохраняет результат.
         *
         *     Результат сохраняется сразу, но к профилю не прикрепляется: это делает
         *     отдельная кнопка «Сохранить в профиль» (ТЗ 1.6).
         */
        post: operations["submit_api_v1_career_test_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/career-test/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Вакансии по профилю направления
         * @description Число открытых вакансий по профессиям направления.
         *
         *     Данные из открытого API hh.ru с кэшем на шесть часов; если источник не
         *     ответил, отдаются последние сохранённые числа с пометкой `stale`
         *     (уточнение У14). Пустой список означает, что источник молчит и в кэше
         *     ничего нет, — интерфейс скажет об этом прямо, а не покажет ноль вакансий.
         */
        get: operations["read_vacancies_api_v1_career_test_vacancies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Отслеживаемые вузы
         * @description Список вузов, добавленных в блоке 2 (ТЗ 3.2).
         *
         *     Пустой список — не ошибка: экран покажет объяснение и кнопку в блок 2
         *     (ТЗ 3.3), а не сообщение о сбое.
         */
        get: operations["read_tracked_api_v1_tracker_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracker/{university_id}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * История изменений позиции
         * @description Текущее место, предыдущее, динамика за неделю и вся история (ТЗ 3.6).
         */
        get: operations["read_positions_api_v1_tracker__university_id__positions_get"];
        put?: never;
        /**
         * Ручной ввод текущей позиции
         * @description Человек называет своё место сам (ТЗ 3.5).
         *
         *     Каждый ввод — новая строка истории, а не замена предыдущей: движение по
         *     списку и есть то, ради чего блок существует.
         */
        post: operations["save_position_api_v1_tracker__university_id__positions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/universities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Справочник вузов
         * @description Список для выбора вуза в профиле.
         *
         *     Цифры приёмной кампании демонстрационные и помечены полем `demo_fields`
         *     в каждой записи (уточнения У4, Д3).
         */
        get: operations["list_universities_api_v1_universities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий профиль */
        get: operations["read_profile_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить профиль
         * @description Меняет статус, вуз, группу или имя.
         *
         *     Пропущенное поле не меняется. Ответ содержит пересчитанный блок `access`:
         *     какие разделы открылись или закрылись, решает сервер, а не клиент (ТЗ 3).
         */
        patch: operations["update_profile_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подтвердить статус студента
         * @description Переводит профиль в подтверждённое состояние.
         *
         *     Реальной проверки учебной почты и загрузки документов нет — это осознанная
         *     заглушка (уточнение У7). Условия подтверждения проверяются настоящие
         *     (уточнение У17), поэтому подключение реальной проверки затронет ровно одну
         *     функцию.
         */
        post: operations["confirm_verification_api_v1_users_me_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vuz-selection/directions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Справочник направлений
         * @description Направления с обязательными предметами: их показывает экран подбора.
         */
        get: operations["read_directions_api_v1_vuz_selection_directions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vuz-selection/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Вузы с метками шанса
         * @description Список направлений в вузах, отсортированный по шансу (ТЗ 2.5).
         *
         *     Расчёт детерминированный и живёт в сервисном слое, а не в LLM: это
         *     арифметика на исторических проходных баллах (тех. ТЗ 3.3).
         */
        get: operations["read_matches_api_v1_vuz_selection_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vuz-selection/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Сохранённые баллы ЕГЭ
         * @description Баллы хранятся на сервере: они не должны расходиться между устройствами (ТЗ 0.2).
         */
        get: operations["read_scores_api_v1_vuz_selection_scores_get"];
        put?: never;
        /**
         * Сохранить баллы ЕГЭ
         * @description Заменяет набор баллов целиком: снятый предмет не должен влиять на выдачу.
         */
        post: operations["save_scores_api_v1_vuz_selection_scores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vuz-selection/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Предметы ЕГЭ и границы проверки
         * @description Список предметов для мультивыбора (ТЗ 2.2) и границы балла (ТЗ 2.3).
         */
        get: operations["read_subjects_api_v1_vuz_selection_subjects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vuz-selection/track/{university_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отслеживать этот вуз
         * @description Добавляет вуз в отслеживаемые (ТЗ 2.7). Повторное нажатие ничего не меняет.
         */
        post: operations["track_api_v1_vuz_selection_track__university_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vuz-selection/universities/{university_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Карточка вуза
         * @description Бюджет, стоимость, общежитие, дата окончания приёма и шансы (ТЗ 2.6).
         *
         *     Отвечает и без введённых баллов: карточка открывается в том числе по
         *     прямой ссылке, и тупика на ней быть не должно (ТЗ 1.1).
         */
        get: operations["read_university_card_api_v1_vuz_selection_universities__university_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Живость процесса */
        get: operations["liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Готовность к запросам */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerOptionOut */
        AnswerOptionOut: {
            /** Id */
            id: number;
            /** Order */
            order: number;
            /** Text */
            text: string;
        };
        /**
         * Chance
         * @description Метка шанса. Подпись, точки и эмодзи рисует интерфейс (уточнение Д1).
         * @enum {string}
         */
        Chance: "high" | "borderline" | "unlikely";
        /** DependencyStatus */
        DependencyStatus: {
            /** Error */
            error?: string | null;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
        };
        /** DirectionMatchOut */
        DirectionMatchOut: {
            /** Code */
            code: string;
            /** Match Percent */
            match_percent: number;
            /** Name */
            name: string;
            /** Summary */
            summary: string;
        };
        /** DirectionOut */
        DirectionOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Required Subjects */
            required_subjects: string[];
            /** Summary */
            summary: string;
        };
        /**
         * ExamScoresIn
         * @description Баллы ЕГЭ: предмет → балл.
         *
         *     Диапазон проверяется и здесь, и в сервисном слое: схема даёт клиенту
         *     внятную ошибку сразу, но источник истины — сервер (тех. ТЗ 8.7).
         */
        ExamScoresIn: {
            /**
             * Scores
             * @description Балл от 0 до 100 по каждому предмету
             */
            scores: {
                [key: string]: number;
            };
        };
        /** ExamScoresOut */
        ExamScoresOut: {
            /**
             * Min Subjects
             * @default 3
             */
            min_subjects: number;
            /** Scores */
            scores: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LivenessResponse */
        LivenessResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * MatchOut
         * @description Программа с меткой шанса (ТЗ 2.5, уточнения У11, У12, Д1).
         */
        MatchOut: {
            /** Applicant Score */
            applicant_score: number;
            /** Budget Places */
            budget_places: number;
            chance: components["schemas"]["Chance"];
            /**
             * Demo Fields
             * @description Поля с демонстрационными значениями, а не официальными данными
             */
            demo_fields?: string[];
            direction: components["schemas"]["DirectionOut"];
            /** Passing Score */
            passing_score: number;
            /** Program Id */
            program_id: number;
            university: components["schemas"]["UniversityBriefOut"];
        };
        /** MatchesOut */
        MatchesOut: {
            /** Items */
            items: components["schemas"]["MatchOut"][];
            /** Total */
            total: number;
        };
        /** PositionEntryOut */
        PositionEntryOut: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Estimated Passing Score */
            estimated_passing_score: number | null;
            /** Position */
            position: number;
        };
        /**
         * PositionIn
         * @description Ручной ввод места (ТЗ 3.5).
         */
        PositionIn: {
            /** Position */
            position: number;
        };
        /**
         * PositionsOut
         * @description История позиции по одному вузу (ТЗ 3.5, 3.6).
         */
        PositionsOut: {
            /** Checked At */
            checked_at: string | null;
            direction: components["schemas"]["TrackedDirectionOut"] | null;
            /** Estimated Passing Score */
            estimated_passing_score: number | null;
            /** History */
            history: components["schemas"]["PositionEntryOut"][];
            /** Improvement */
            improvement: number | null;
            /**
             * Max Position
             * @default 9999
             */
            max_position: number;
            /**
             * Min Position
             * @default 1
             */
            min_position: number;
            /** Position */
            position: number | null;
            /** Previous Position */
            previous_position: number | null;
            university: components["schemas"]["TrackedUniversityOut"];
            /** Week */
            week: components["schemas"]["WeekPointOut"][];
        };
        /**
         * ProfileAccessOut
         * @description Какие разделы открыты. Считает сервер (ТЗ 3).
         */
        ProfileAccessOut: {
            /**
             * Answer Questions
             * @description Право отвечать в блоке 5 (уточнение У17)
             */
            answer_questions: boolean;
            /**
             * Food
             * @description Блок 7 «Где покушать»
             */
            food: boolean;
            /**
             * Schedule
             * @description Блок 4 «Расписание и дедлайны»
             */
            schedule: boolean;
        };
        /** ProfileOut */
        ProfileOut: {
            access: components["schemas"]["ProfileAccessOut"];
            /** Display Name */
            display_name: string;
            /** Group Name */
            group_name: string | null;
            /** Is Verified Student */
            is_verified_student: boolean;
            /** Max User Id */
            max_user_id: string;
            /**
             * Needs Display Name
             * @description Имя не получено от платформы и не введено пользователем — профиль должен показать строку ввода имени (уточнение У6).
             */
            needs_display_name: boolean;
            /** Points Balance */
            points_balance: number;
            status: components["schemas"]["UserStatus"];
            university: components["schemas"]["UniversityOut"] | null;
        };
        /**
         * ProfileUpdateIn
         * @description Частичное обновление профиля.
         *
         *     Пропущенное поле означает «не менять». Очистки полей нет: вуз и группа
         *     выбираются из списка, имя не стирается.
         */
        ProfileUpdateIn: {
            /** Display Name */
            display_name?: string | null;
            /** Group Name */
            group_name?: string | null;
            status?: components["schemas"]["UserStatus"] | null;
            /** University Id */
            university_id?: number | null;
        };
        /** QuestionOut */
        QuestionOut: {
            /** Id */
            id: number;
            /** Options */
            options: components["schemas"]["AnswerOptionOut"][];
            /** Order */
            order: number;
            /** Text */
            text: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Dependencies */
            dependencies: components["schemas"]["DependencyStatus"][];
            /** Status */
            status: string;
        };
        /**
         * SavedResultOut
         * @description Ответ на «Сохранить в профиль» (ТЗ 1.6).
         */
        SavedResultOut: {
            /** Points Balance */
            points_balance: number;
            /** Points Granted */
            points_granted: boolean;
            result: components["schemas"]["TestResultOut"];
        };
        /**
         * SubjectsOut
         * @description Список предметов и границы проверки — чтобы клиент их не выдумывал.
         *
         *     Экран подбора рисует ровно эти кнопки и проверяет ровно эти границы. Свой
         *     список на клиенте разошёлся бы со справочником направлений в первый же раз,
         *     когда справочник поменяется (ТЗ 2.2, 2.3).
         */
        SubjectsOut: {
            /**
             * Max Score
             * @default 100
             */
            max_score: number;
            /**
             * Min Score
             * @default 0
             */
            min_score: number;
            /**
             * Min Subjects
             * @default 3
             */
            min_subjects: number;
            /** Subjects */
            subjects?: string[];
        };
        /**
         * SubmitIn
         * @description Ответы: по одному варианту на каждый вопрос теста.
         */
        SubmitIn: {
            /** Option Ids */
            option_ids: number[];
        };
        /** TestResultOut */
        TestResultOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Explanation */
            explanation: string;
            /** Id */
            id: number;
            /** Profile */
            profile: {
                [key: string]: number;
            };
            /** Saved To Profile */
            saved_to_profile: boolean;
            /** Top Directions */
            top_directions: components["schemas"]["DirectionMatchOut"][];
        };
        /** TrackIn */
        TrackIn: {
            /** Direction */
            direction?: string | null;
        };
        /** TrackedDirectionOut */
        TrackedDirectionOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** TrackedItemOut */
        TrackedItemOut: {
            direction: components["schemas"]["TrackedDirectionOut"] | null;
            /** Position */
            position: number | null;
            university: components["schemas"]["TrackedUniversityOut"];
        };
        /** TrackedListOut */
        TrackedListOut: {
            /** Items */
            items: components["schemas"]["TrackedItemOut"][];
            /** Total */
            total: number;
        };
        /** TrackedOut */
        TrackedOut: {
            direction: components["schemas"]["DirectionOut"] | null;
            university: components["schemas"]["UniversityBriefOut"];
        };
        /**
         * TrackedUniversityOut
         * @description Вуз в списке отслеживаемых.
         *
         *     Своя схема, а не импорт из чужого домена: домены не импортируют схемы друг
         *     друга (тех. ТЗ 1.1).
         */
        TrackedUniversityOut: {
            /** Admission Deadline */
            admission_deadline: string | null;
            /** City */
            city: string;
            /** Id */
            id: number;
            /** Short Name */
            short_name: string;
        };
        /**
         * UniversityBriefOut
         * @description Вуз в выдаче блока 2.
         *
         *     Своя схема, а не импорт из домена users: домены не импортируют схемы друг
         *     друга (тех. ТЗ 1.1). Модель при этом общая — её отдаёт сервисный слой
         *     users, и дублируется только форма ответа.
         */
        UniversityBriefOut: {
            /** Address */
            address: string;
            /** Admission Deadline */
            admission_deadline: string | null;
            /** Budget Places */
            budget_places: number | null;
            /** City */
            city: string;
            /** Has Dormitory */
            has_dormitory: boolean;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Short Name */
            short_name: string;
            /** Tuition Price */
            tuition_price: number | null;
        };
        /**
         * UniversityCardOut
         * @description Карточка вуза (ТЗ 2.6, 2.7).
         */
        UniversityCardOut: {
            /**
             * Demo Fields
             * @description Поля с демонстрационными значениями, а не официальными данными
             */
            demo_fields?: string[];
            /** Programs */
            programs: components["schemas"]["MatchOut"][];
            /** Tracked */
            tracked: boolean;
            university: components["schemas"]["UniversityBriefOut"];
        };
        /** UniversityOut */
        UniversityOut: {
            /**
             * Address
             * @description Адрес корпуса, к которому относятся координаты
             */
            address: string;
            /** Admission Deadline */
            admission_deadline: string | null;
            /** Budget Places */
            budget_places: number | null;
            /** City */
            city: string;
            /**
             * Demo Fields
             * @description Поля с демонстрационными значениями: цифры приёмной кампании не являются официальными данными и должны быть помечены в интерфейсе.
             */
            demo_fields?: string[];
            /** Has Dormitory */
            has_dormitory: boolean;
            /** Id */
            id: number;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Name
             * @description Полное официальное название
             */
            name: string;
            /**
             * Short Name
             * @description Короткое название для интерфейса
             */
            short_name: string;
            /**
             * Tuition Price
             * @description Стоимость года обучения в рублях
             */
            tuition_price: number | null;
        };
        /**
         * UserStatus
         * @description Статус пользователя (ТЗ 1.3).
         *
         *     Значение по умолчанию — «Абитуриент»: онбординга нет, новый пользователь
         *     попадает сразу в главное меню (уточнение У5).
         * @enum {string}
         */
        UserStatus: "school" | "applicant" | "student";
        /**
         * VacanciesOut
         * @description Вакансии по профилю направления (ТЗ 1.5, уточнение У14).
         */
        VacanciesOut: {
            /** Direction */
            direction: string;
            /** Items */
            items: components["schemas"]["VacancyCountOut"][];
            /** Source */
            source: string;
            /** Stale */
            stale: boolean;
        };
        /** VacancyCountOut */
        VacancyCountOut: {
            /** Count */
            count: number;
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeekPointOut */
        WeekPointOut: {
            /** Position */
            position: number | null;
            /** Weekday */
            weekday: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_questions_api_v1_career_test_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"][];
                };
            };
        };
    };
    read_latest_result_api_v1_career_test_results_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResultOut"];
                };
            };
            /** @description Тест ещё не пройден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    save_result_api_v1_career_test_results__result_id__save_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_api_v1_career_test_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_vacancies_api_v1_career_test_vacancies_get: {
        parameters: {
            query: {
                direction: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacanciesOut"];
                };
            };
            /** @description Направления с таким кодом нет */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_tracked_api_v1_tracker_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedListOut"];
                };
            };
        };
    };
    read_positions_api_v1_tracker__university_id__positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                university_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionsOut"];
                };
            };
            /** @description Этот вуз пользователь не отслеживает */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_position_api_v1_tracker__university_id__positions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                university_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionsOut"];
                };
            };
            /** @description Этот вуз пользователь не отслеживает */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_universities_api_v1_universities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversityOut"][];
                };
            };
        };
    };
    read_profile_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    update_profile_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_verification_api_v1_users_me_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    read_directions_api_v1_vuz_selection_directions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectionOut"][];
                };
            };
        };
    };
    read_matches_api_v1_vuz_selection_matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchesOut"];
                };
            };
        };
    };
    read_scores_api_v1_vuz_selection_scores_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamScoresOut"];
                };
            };
        };
    };
    save_scores_api_v1_vuz_selection_scores_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamScoresIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamScoresOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_subjects_api_v1_vuz_selection_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectsOut"];
                };
            };
        };
    };
    track_api_v1_vuz_selection_track__university_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                university_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedOut"];
                };
            };
            /** @description Вуза или направления с таким идентификатором нет */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_university_card_api_v1_vuz_selection_universities__university_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                university_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversityCardOut"];
                };
            };
            /** @description Вуза с таким идентификатором нет */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
